In [1]:
import numpy as np
import random

### 6 Solve the system of equations 3 x0 + x1 = 9 and x0 + 2 x1 = 8

In [10]:
a = np.array([[3,1],[1,2]])
b = np.array([9,8])
a = np.linalg.solve(a,b)
np.round(a,1)
# np.max(a)

array([2., 3.])

In [ ]:

1. Find dot product of two arrays.¶

In [13]:
np.dot([2j, 3j], [2j, 3j])

(-13+0j)

2. Create two arrays of 2-D and find dot product of it.¶

In [16]:
a =np.array([[1, 3], [0, 1]])
b = np.array([[4, 1], [2, 2]])
np.dot(a,b)

array([[10,  7],
       [ 2,  2]])


###3. Find vector product of given array.
a = np.array([1+2j,3+4j])

b = np.array([5+6j,7+8j])

In [18]:
a = np.array([1+2j,3+4j])

b = np.array([5+6j,7+8j])
np.cross(a,b)

array(0.-16.j)


###4. FIrst create given array withound using direct value insted use numpy utlities and then find inner product for given array.
a = [[ 0 1 2 3] [ 4 5 6 7] [ 8 9 10 11]]

b = [[12 13 14 15] [16 17 18 19] [20 21 22 23]]

In [49]:
a = np.arange(0,12).reshape(3,4)
b = np.arange(12,24).reshape(4,3)
np.matmul(a,b)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

###5
5. Using given two array try to print out 3rd given array.
a = np.array(['a', 'b', 'c'], dtype=object) b = np.array([1,2,3])

output = [['a', 'aa', 'aaa'], ['b', 'bb', 'bbb'], ['c', 'cc', 'ccc']]

In [32]:
a = np.array(['a', 'b', 'c'])
b = np.array([1,2,3])
m = []
for i in a:
    m.append(np.char.multiply(i,b))
print(m)
    

[array(['a', 'aa', 'aaa'], dtype='<U3'), array(['b', 'bb', 'bbb'], dtype='<U3'), array(['c', 'cc', 'ccc'], dtype='<U3')]



7. Check the following solution is right or wrong uisng numpy utilities.
2x+3y=8 3x+y=5

solution: x=1 , y=2

In [39]:
a = np.array([[2,3],[3,1]])
b = np.array([8,5])
x = np.array([1,2])
# np.linalg.solve(a,b)
np.allclose(np.dot(a,x),b)

True


9. Write a program to add two arrays of different shape.
Hint: Broadcasting

Level: Medium

sample input:

a=[0.0,10.0,20.0,30.0]

b=[1.0,2.0,3.0]

In [41]:
a = np.array([0.0,10.0,20.0,30.0]).reshape(4,1)
b = np.array([1.0,2.0,3.0])
a+b


array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])


10. Create a 3 * 3 array find it's diagonal using numpy utilities.

In [49]:
a = np.random.randint(1,100,(3,3))
print(a)
np.diag(a)

[[54 88 31]
 [95 70 68]
 [32 97  6]]


array([54, 70,  6])


11. Now find anti - diagonal in previous question using horizontal and vector flip.
Level: Hardb

In [57]:
a = np.random.randint(1,100,(3,3))
print(a)
b = np.fliplr(a).diagonal() # Horizontal flip
c = np.flipud(a).diagonal() # vertical flip
f = np.diag(a, k= 1)

print(b,c,f)

[[49 39 50]
 [25 18  3]
 [34 68 79]]
[50 18 34] [34 18 50] [39  3]



12. Create given array without using indexing.
a = [[4, 0, 0], [0, 4, 0], [0, 0, 4], [0, 0, 0], [4, 0, 0], [0, 4, 0], [0, 0, 4]]

In [89]:
a = np.zeros((7,3))
np.fill_diagonal(a,4,wrap = True)

print(a)
        
    
    

[[4. 0. 0.]
 [0. 4. 0.]
 [0. 0. 4.]
 [0. 0. 0.]
 [4. 0. 0.]
 [0. 4. 0.]
 [0. 0. 4.]]
