In [2]:
import numpy as np

In [5]:
print(np.version.version)
print(np.__config__)

1.16.5
<module 'numpy.__config__' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\__config__.py'>



2. Create a null vector of size 10 but the fifth value which is 1.

In [6]:
ten_zeros = np.zeros(10)
ten_zeros[4] = 1
print(ten_zeros)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


3.Create a vector with values ranging from 10 to 49.

In [13]:
range_49 = np.arange(10,49)
print(range_49)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]



3. create two arrays and stack them vertically¶

In [22]:
import random
a = np.random.randint(1,50,(4,5))
b =  np.random.randint(50,150,(4,5)) 
np.vstack((a,b))

array([[  5,   7,   6,   8,  49],
       [ 36,  21,  13,  38,  31],
       [ 43,  26,  45,  10,   2],
       [  5,  10,  13,  12,  18],
       [ 99, 104,  63, 144,  70],
       [ 71, 114,  98,  73, 120],
       [ 94,  88,  88, 119, 122],
       [ 90,  50,  73, 133,  78]])

4. Reverse a vector (first element becomes last).

In [29]:
a = np.arange(1,30)
print(a[::-1])

[29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6
  5  4  3  2  1]


5. Create a 3x3 matrix with values ranging from 0 to 8

In [27]:
a = np.random.randint(0,8,(3,3))
print(a)

[[5 3 3]
 [0 4 4]
 [2 4 2]]


6. Find indices of non-zero elements from [1,2,0,0,4,0]

In [13]:
non_zero = np.array([1,2,0,0,4,0])
a = np.where(non_zero!= 0)
print(a)

(array([0, 1, 4], dtype=int64),)


7.  Create a 10x10 array with random values and find the minimum and maximum values.

In [11]:
min_max =  np.random.randint(0,100,(10,10))
print(min_max)
print(np.max(min_max))
print(np.min(min_max))

[[32  5 54 12 38 77 58  4 52 75]
 [82 94 27 28 95 42 63 39 35 10]
 [28 10 74 58 80  8 96 22 14 39]
 [58  3 80 68 27 82 19 58 74 73]
 [ 4 58 74  5 39 19 43 28 47 37]
 [35 94 43 34  6 52 74 14 56 86]
 [79 49 46 24 39 69 48 31  6 43]
 [66 21 98 32  0 39  8  7 23 96]
 [24 77 52 56 42 26 56 69 97 35]
 [75 24 91 39 45 10 82 46 10 10]]
98
0


8.Create a random vector of size 30 and find the mean value.

In [14]:
import random

In [35]:
vector = np.arange(1,31,(1))
print(vector)


mean =  np.sum(vector)//vector.size


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
15


30

9. Create a 2d array with 1 on the border and 0 inside¶

In [68]:
oneborder = np.ones((10,10))
# oneborder[1:-1,1:-1] =  2
oneborder[0:-1]= 2
print(oneborder)

[[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
10.9. Create a 2d array with 0 on the border and 1 inside¶


In [73]:
oneborder =  np.zeros((10,10))
# print(oneborder)
oneborder[0,:] = 1
oneborder[-1,:] = 1
oneborder[:,0] = 1
oneborder[:,-1] = 1
print(oneborder)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


Create a 5x5 matrix with values 1,2,3,4 just below the diagonal¶

In [75]:
diagonal = np.zeros((5,5))
for  i in range(5):
    diagonal[i,i] = i
print(diagonal)

[[0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 2. 0. 0.]
 [0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 4.]]


Create a 5*5 matrix with random values and normalize it.

In [81]:
a = np.random.randint(0,111,(5,5))
y = (a-(a.max()))/(a.max()- a.min())
y

array([[-0.00970874, -0.27184466, -1.        , -0.94174757, -0.49514563],
       [-0.55339806, -0.5631068 , -0.62135922, -0.96116505, -0.6407767 ],
       [-0.6407767 , -0.33009709, -0.89320388, -0.00970874, -0.74757282],
       [ 0.        , -0.87378641, -0.53398058, -0.73786408, -0.34951456],
       [-0.34951456, -0.69902913, -0.05825243, -0.05825243, -0.30097087]])

13. How to find common values between two arrays

In [84]:
a = np.arange(25)
b = np.arange(10,51)
print(np.intersect1d(a,b))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


14. Consider a generator function that generates 10 integers and use it to build an array

In [92]:
def generator():
    a = np.arange(10)
    return a
generator()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

15. Subtract the mean of each row of a matrix

In [105]:
a = np.random.randint(0,111,(5,5))
means = np.mean(a, axis = 1)
sub = a.copy()
for i in range(5):
#     b = a[i,:]
#     b.mean()
    sub[i] = sub[i] - means[i]

print(sub)
# print(a)

[[-13 -49  58  -9  14]
 [  5  45 -26 -23   0]
 [-16 -11  16   8   2]
 [ 32  20   6  -3 -56]
 [  7   2  42 -41 -11]]


16. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?¶

In [133]:
a = np.random.randint(1,10,(1,3))
b = np.random.randint(1,10,(3,1))


sums = []
for i in np.nditer(a):
    for j in np.nditer(b):
        sums.append(i+j)
print(np.array(sums).reshape(3,3))



[[12 14 13]
 [12 14 13]
 [ 8 10  9]]


In [130]:
a = np.random.randint(1,10,(1,3))
b = np.random.randint(1,10,(3,1))
c = b.reshape(1,3)
print(a+b)

[[ 6  9 11]
 [ 7 10 12]
 [ 5  8 10]]



17. Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50

In [147]:
a = np.arange(5,50,10)
print(a)
#for step we can use arange 0r
b = np.arange(50)
# print(b)
b[5:-1:10]


[ 5 15 25 35 45]


array([ 5, 15, 25, 35, 45])