
1. Create an array and find sum of it.

In [2]:
import numpy as np
import random

In [3]:
a = np.array([1,2,3,5,6,7,8])
print(a.sum())

32



2. Find sin of given array.

In [5]:
a = np.array([1,2,3,5,6,7,8])
print(np.sin(a))

[ 0.84147098  0.90929743  0.14112001 -0.95892427 -0.2794155   0.6569866
  0.98935825]


In [ ]:

3. Find mean of matrix along row and column.

In [10]:
a = np.random.randint(1,100,(5,5))
print(np.mean(a, axis = 0))
print(np.mean(a,axis = 1))



[63.2 41.6 46.6 56.  58.6]
[48.  51.4 63.6 60.4 42.6]
53.2




4. Find standard deviation of given array.¶

In [12]:
import math

In [15]:
a = np.array([1,2,3,5,6,7,8])
np.std(a)

2.4411439272335804


5. Create a 3*3 matrix and print it's transpose matrix¶


In [20]:
a = np.random.randint(1,100,(3,3))
print(a)
np.transpose(a)

[[47 49  4]
 [33 19 33]
 [16 16 90]]


array([[47, 33, 16],
       [49, 19, 16],
       [ 4, 33, 90]])

6. Create an array of 3*3 and find index of max along both axis.¶

In [43]:
a = np.random.randint(1,100,(3,3))
print(a)
# b = np.max(a)
np.where(a == np.max(a))
# np.argmax(a)

[[82 88 38]
 [98 83 82]
 [34 99 40]]


(array([2], dtype=int64), array([1], dtype=int64))

# 8. to find max indicees along the  both the  axis

In [33]:
np.argmax(a,axis =0)


array([2, 1, 0], dtype=int64)

In [34]:
np.argmax(a, axis = 1)

array([2, 1, 0], dtype=int64)

In [ ]:

7. find sum of two matrix.¶

In [44]:
a = np.random.randint(1,100,(3,3))
b = np.random.randint(1,100,(3,3))
print(a+b)

[[ 56  31  68]
 [139 131  84]
 [ 88  99 144]]


10 Try to solve a array and print a array with indices which would sort the given array.

In [3]:
a = np.array([3,1,8,2])
np.argsort(a)

array([1, 3, 0, 2], dtype=int64)

11. Try to do perform same operation mentioned in previous questions for multidimentional array along both axis.
Level: Medium

In [10]:
a = np.array([[9,7,3],[4,5,6]])
print(np.sort(a, axis =0))
np.argsort(a, axis =0)


[[4 5 3]
 [9 7 6]]


array([[1, 1, 0],
       [0, 0, 1]], dtype=int64)

 calculate multiplication of transpose and matrix itself of a 3*3 matrix.

In [15]:
a = np.random.randint(1,10,(3,3))
np.matmul(a, a.transpose())


array([[ 83, 114, 105],
       [114, 198, 144],
       [105, 144, 133]])

13. Find solution for given linear equstion:

13. Find solution for given linear equstion:
2x + 5y = 28 4x + 3*y = 81

In [17]:
a = np.array([[2,5],[4,3]])
b = np.array([28,81])
np.linalg.solve(a,b)

array([22.92857143, -3.57142857])


14. Find Rank, Trace, Inverse, Determinant of a given matrix.¶

In [19]:
a = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
np.linalg.matrix_rank(a)

1

In [22]:
np.trace(a)

6

In [24]:
np.linalg.inv(a) # if the matrix is not sqaure matrix it will not excegute

LinAlgError: Singular matrix

In [25]:
np.linalg.det(a)

0.0

15. Find cube of a mtrix.

In [30]:
a = np.random.randint(1,10,(3,3))
# np.linalg.matix_power(a,3)
np.linalg.matrix_power(a, 3)

array([[1756, 1692, 2152],
       [1920, 1984, 2404],
       [ 804,  804,  996]])