In [1]:
import numpy as np

In [3]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
np.zeros(4)

array([0., 0., 0., 0.])

In [5]:
np.ones(2)

array([1., 1.])

In [9]:
a =  np.zeros((3,3,3))
print(a)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [11]:
a.shape

(3, 3, 3)

In [14]:
a = np.full((4,4),5)
for i in range(5):
    for j in range(5):
        print(a[1][3])

5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5


In [15]:
import random

In [22]:
 
s = np.random.randint(1,10,(3,3))

In [23]:
s.ndim

2

In [24]:
s.shape

(3, 3)

In [25]:
s.size

9

In [30]:
a = np.random.randint(100,200,(5,4,3))
print(a)

[[[118 192 189]
  [157 149 112]
  [190 148 127]
  [104 160 185]]

 [[129 196 186]
  [109 161 185]
  [166 109 127]
  [161 138 131]]

 [[100 114 161]
  [152 130 120]
  [151 132 101]
  [143 165 180]]

 [[193 170 127]
  [143 111 132]
  [180 163 134]
  [127 149 101]]

 [[129 197 199]
  [185 196 100]
  [191 167 189]
  [104 195 114]]]


In [42]:
a = np.random.randint(100,200,(5,4))
print(a)
a[0:2,0:2]
a[1:2,2]

[[192 134 113 173]
 [168 106 178 192]
 [104 103 111 108]
 [168 123 118 120]
 [147 132 117 162]]


array([178])

In [18]:
np.random.rand()

0.7105374156461842

In [31]:
a[2:2]

array([], shape=(0, 4, 3), dtype=int32)

In [2]:
import numpy as np

In [6]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)
# to find the specfic value lets say 10 i,e [rowindex , columnindex]
print(a[1,2])
# or we can use negative indexing as in lists
print(a[-1,-5])
print(a[1,-5])


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
10
10
10


In [12]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
# print(a)
# to get specific row i.e [row, :]
print(a[0,:])
(a[0,:]) = 0
(a[1,:]) = 0
print(a)


[1 2 3 4 5 6 7]
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [16]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
# print(a)
# to get specific column i.e [: ,columnindex]
print(a[:,3])
(a[:,4]) = 0
print((a[:,4]))

[ 4 11]
[0 0]


In [60]:
a = np.zeros((5,5))
a[1:4,1:4] = 3
print(a)

[[0. 0. 0. 0. 0.]
 [0. 3. 3. 3. 0.]
 [0. 3. 3. 3. 0.]
 [0. 3. 3. 3. 0.]
 [0. 0. 0. 0. 0.]]


In [20]:
# to get fancy i.e is to fetch middle values of a row zero apart from starting and ending i.e [select row, startindex:endindex:step]
print(a[0,1:-1])
# if we need op as 2 4 6 i.e is step 2
print(a[0,1:-1:2])

[2 3 4 0 6]
[2 4 6]


In [26]:
# to get fancy i.e is to fetch middle values of a row zero apart from starting and ending i.e [select row, startindex:endindex:step]
print(a[1:-1:,2])
# if we need op as 2 4 6 i.e is step 2
print(a[0,1:-1:2])

[]
[2 4 6]


In [31]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
#To make 2 column vales as zero  and to give some values to it\
a[:,2] = 0
print(a)
a[:,2] = [1,2]
print(a)


[[ 1  2  0  4  5  6  7]
 [ 8  9  0 11 12 13 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 13 14]]


In [40]:
# same way to make it columms
a[0,:] =  0
print(a)
a [1,:] =2
print(a)

[[0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1]]
[[0 0 0 0 0 0 0]
 [2 2 2 2 2 2 2]]


In [41]:
import random

In [51]:
a = np.random.randint(10,100,(5,5))
print(a)
a[0:,0:]= 0
print(a)
a[1:-1,1:-1] = 1
print(a)
a[0,0:]= 5
a[-1,0:] =5
a[:,0] = 5
a[:,-1] =5
print(a)


[[15 82 45 57 50]
 [71 17 37 44 59]
 [42 90 27 73 47]
 [88 65 35 20 71]
 [20 11 16 73 14]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]
[[5 5 5 5 5]
 [5 1 1 1 5]
 [5 1 1 1 5]
 [5 1 1 1 5]
 [5 5 5 5 5]]


In [57]:
a = np.zeros((2,2,2))
print(a)
a[:,1,:] = [[6,7],[8,9]]
print(a)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
[[[0. 0.]
  [6. 7.]]

 [[0. 0.]
  [8. 9.]]]


BooleanMasking and advaced indexing

In [67]:
a = np.random.randint(10,100,(5,5))
print(a)
s = a[a<50] # to find the values which are greater than a given number in a  array

[[98 79 76 65 77]
 [58 52 62 90 65]
 [17 87 60 58 21]
 [25 95 20 89 89]
 [93 86 73 76 46]]


Create a 5*5 matrix with random values and normalize it.

In [69]:
print(s)
# we can index with list in numpy i.e
s[[1,4]]


[17 21 25 20 46]


array([21, 46])

How to find common values between two arrays

In [73]:
np.all

<function numpy.all(a, axis=None, out=None, keepdims=<no value>)>