In [2]:
import random
import numpy as np
import collections

### 1. Count The Number Of Times Each Value Appears In An Array Of Integers¶

In [15]:
a = np.random.randint(0,4,20)
collections.Counter(a)

Counter({0: 7, 1: 6, 3: 4, 2: 3})

In [ ]:
###OR

In [22]:
a = np.random.randint(0,4,20)
unique, counts = np.unique(a, return_counts=True)
dict(zip(unique, counts))


{0: 7, 1: 6, 2: 4, 3: 3}

#2. Given 9 Integers. You have to convert them into 3*3 Numpy array using Reshape function.

In [27]:
a = np.ones((1,9))
np.reshape(a,(3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])


3. How to find the memory size of any array¶

In [33]:
a = np.zeros((4,4))
memory = a.size * a.itemsize
print(memory,"bytes")

128 bytes


4. Create a 2d array of size 10 by 10 with 1 on the border and 0 inside.

In [40]:
a = np.ones((10,10))
a[1:-1,1:-1] = 0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])


5.Create a 8x8 matrix and fill it with a checkerboard pattern.

In [63]:
a = np.zeros((8,8))
a[1::2,::2] = 1
a[::2,1::2] = 1
print("Checkerboard pattern, Where 1 == White, 0 == Black")
print(a)




Checkerboard pattern, Where 1 == White, 0 == Black
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


6. Normalize a 5x5 random matrix.
normalization formula : ((a-mean(a))/std(a))

In [66]:
a = np.random.randint(1,7,(5,5))
b = (a- a.mean())/(np.std(a))
print(b)

[[ 0.89417953  0.30590352 -1.4589245   1.48245554 -1.4589245 ]
 [ 1.48245554  0.30590352 -0.28237248 -0.28237248 -1.4589245 ]
 [-0.28237248 -0.87064849 -0.87064849  0.89417953 -0.28237248]
 [ 0.30590352 -0.28237248 -0.28237248 -1.4589245   0.30590352]
 [ 0.89417953  1.48245554 -1.4589245   1.48245554  0.89417953]]


7. Given a 1D array in range(0,11), negate all elements which are between 3 and 8, in place.¶

In [88]:
a = np.arange(12)
# print(a)
m = np.where((a<3) | (a>8))
print(m)

(array([ 0,  1,  2,  9, 10, 11], dtype=int64),)


In [ ]:
8. How to get the dates of yesterday, today and tomorrow?

In [104]:
yesterday = np.datetime64("today","D") -np.timedelta64(1,"D")
print("Yesterday"  ,yesterday)

today = np.datetime64("today"      ,"D") 
print("Today",today)
Tomorrow = np.datetime64("today"  ,"D") +np.timedelta64(1,"D")
print("Tomorrow",Tomorrow)

Yesterday 2020-02-13
Today 2020-02-14
Tomorrow 2020-02-15


In [ ]:

9. Generate two arrays of size 2X4 & 3X3, find difference between them.¶

In [138]:
a = np.ones((2,4))
b = np.full((3,3),4)
a[:, np.newaxis] + b


ValueError: operands could not be broadcast together with shapes (2,1,4) (3,3) 


10. Given 1d array of ['cat','dog','rat'], genrate 100 elements of 1d array consisting of the above 3 value ?
['cat','cat',...,'rat','dog','dog','cat'...]

In [142]:
a = np.random.randint(0,3,100)
np.choose(a, choices = ['cat','dog','rat']) 


array(['rat', 'cat', 'rat', 'rat', 'rat', 'cat', 'cat', 'dog', 'cat',
       'cat', 'rat', 'cat', 'rat', 'dog', 'dog', 'rat', 'dog', 'cat',
       'rat', 'cat', 'rat', 'dog', 'dog', 'cat', 'cat', 'dog', 'rat',
       'rat', 'rat', 'rat', 'cat', 'cat', 'dog', 'cat', 'dog', 'cat',
       'cat', 'cat', 'cat', 'rat', 'dog', 'dog', 'cat', 'rat', 'rat',
       'dog', 'cat', 'rat', 'dog', 'rat', 'cat', 'cat', 'dog', 'rat',
       'rat', 'rat', 'cat', 'dog', 'cat', 'rat', 'dog', 'cat', 'rat',
       'rat', 'dog', 'cat', 'dog', 'dog', 'rat', 'cat', 'cat', 'cat',
       'dog', 'dog', 'cat', 'cat', 'cat', 'rat', 'rat', 'dog', 'rat',
       'cat', 'cat', 'rat', 'cat', 'cat', 'dog', 'rat', 'cat', 'dog',
       'rat', 'rat', 'dog', 'dog', 'dog', 'rat', 'cat', 'rat', 'dog',
       'rat'], dtype='<U3')


11. Create a vector of size 10 with values ranging from 0 to 1, both excluded without manually deducing the values

In [151]:
a = np.linspace(0,1,12)[1:-1]
print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]



12. Given a two dimensional array, how to extract unique rows?

In [166]:
a = np.random.randint(1,16,(4,4))
np.unique(a, axis = 1)

array([[10, 10, 11, 13],
       [ 2, 11, 10, 13],
       [10, 13,  4, 12],
       [13, 12,  1, 15]])

13. Create a structured array with x and y coordinates covering the [0,1]x[0,1] are

In [186]:
z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                   ('y', float, 1)])])
z

array([((0., 0.),), ((0., 0.),), ((0., 0.),), ((0., 0.),), ((0., 0.),),
       ((0., 0.),), ((0., 0.),), ((0., 0.),), ((0., 0.),), ((0., 0.),)],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')])])

14. How to find the closest value (to a given scalar) in a vector?

In [188]:
x = np.arange(100)

a = np.random.uniform(0,100)
print("Value to compare:")
print(a)
index = (np.abs(x-a)).argmin()
print(x[index])

Value to compare:
37.698153316646554
38


In [ ]:
15. Consider a random vector with shape (10,2) representing coordinates, find point by point distances. Use euclidian distance.

In [195]:
import numpy as np
a= np.random.randint(1,100,(10,2))
x,y = np.atleast_2d(a[:,0], a[:,1])
d = np.sqrt( (x-x.T)**2 + (y-y.T)**2)
print(d)


[[  0.          31.144823    80.04998438  32.75667871  65.
   99.2975327   58.83026432  28.42534081  51.07837116  29.06888371]
 [ 31.144823     0.          49.33558553  20.22374842  34.13209633
   69.35416354  53.          22.84731932  51.19570294  27.73084925]
 [ 80.04998438  49.33558553   0.          61.03277808  22.20360331
   21.26029163  82.66196223  66.57326791  87.1148667   71.28113355]
 [ 32.75667871  20.22374842  61.03277808   0.          40.71854614
   82.20097323  33.13608305   6.08276253  31.04834939  10.29563014]
 [ 65.          34.13209633  22.20360331  40.71854614   0.
   43.18564576  60.46486583  46.61544808  65.06919394  50.99019514]
 [ 99.2975327   69.35416354  21.26029163  82.20097323  43.18564576
    0.         103.40696302  87.658428   108.24509227  92.4175308 ]
 [ 58.83026432  53.          82.66196223  33.13608305  60.46486583
  103.40696302   0.          33.24154028  11.40175425  30.46309242]
 [ 28.42534081  22.84731932  66.57326791   6.08276253  46.61544808
   8

16. How to sort an array by the nth column?

In [8]:
# sort array with regards to nth column
arr = np.array([[1,2,3],[4,2,1],[4,1,2]])
arr = arr[arr[:,2].argsort()]
print(arr)

[[4 2 1]
 [4 1 2]
 [1 2 3]]


In [ ]:
7.How to tell if a given 2D array has null columns?

In [11]:
z = np.random.randint(0,3,(3,10))
print((~z.any(axis=0)).any())


False


18. Considering a two dimensions array, how to get sum over the last two columns at once?

In [18]:
a = np.random.randint(1,100,(5,5))
s = np.sum(a[-2:,])
b = a[-2:,]
print(s,b)

591 [[57 88 95 19 48]
 [31 51 37 84 81]]



19. Given a 2d array of 5X5, increment 1st column by 1, second column by 2, 3rd column by 3 & so on till the last column

In [40]:
a = np.ones((5,5))
# b = a.size[0]
c = []
for i in range (5):
    b = a[i,] + (i+1)
    c.append(b)
print(c)

[array([2., 2., 2., 2., 2.]), array([3., 3., 3., 3., 3.]), array([4., 4., 4., 4., 4.]), array([5., 5., 5., 5., 5.]), array([6., 6., 6., 6., 6.])]


In [ ]:

20. Given a 1d array(size 100) of boolean values, identify total number of True in it.

In [53]:
a = np.random.randint(0,2,(1,100))
unique , counts = np.unique(a, return_counts = True)
d  = dict(zip(unique, counts))
print(d)

{0: 55, 1: 45}


In [ ]:
21.Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value ?

In [59]:
a = np.array([1, 2, 3, 4, 5])
n = 3
b = np.zeros(len(a)+(len(a)-1)*n)
b[::n+1] = a
print(b)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [ ]:
22.How to swap two rows of an array ?

In [72]:
a= np.arange(25).reshape(5,5)
print(a)
a[[0,1]] = a[[1,0]]
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [ ]:
23.How to get the n largest values of an array

In [79]:
z= np.arange(10000)
np.random.shuffle(z)
n = 5
#slow
print(z[np.argsort(z)[-n:]])
 #fast
print(z[np.argpartition(-z,n)[:n]])


[9995 9996 9997 9998 9999]
[9998 9996 9997 9999 9995]


25. How to get index of top two highest value in a 1d array?
[2,22,11,-11,33,7,13,872,-23]

In [5]:
a  = np.array([2,22,11,-11,33,7,13,872,-23])
a.sort()
a[-2:]

array([ 33, 872])


24. Given two random arrays of shape 5X5, identify the common elements between them.

In [6]:
import numpy as np
array1 = np.random.randint(0,9,(5,5))
array2 = np.random.randint(0,9,(5,5))
print(np.intersect1d(array1, array2))

[1 2 3 4 5 6 7 8]
